Added new rules
bigbinary/neeto-monitor-ruby pull request #20
Opened 2023-02-08 09:50 UTC by navaneethsdk

Fixes #19 

@yedhink _a. This repo does not have a gemfile to run rubocop.

2023-02-08 10:53 UTC, yedhink commented
@navaneethsdk _a Please add the Gemfile to this gem. Refer: https://github.com/bigbinary/neetob/blob/main/Gemfile#L15

2023-02-08 11:07 UTC, navaneethsdk commented
@yedhink _a. I have performed the desired changes. Kindly review.

2023-02-08 11:21 UTC, yedhink requested changes
@navaneethsdk _a

2023-02-08 11:21 UTC, yedhink commented on Gemfile
> +  gem "terminal-table", "~> 3.0.2"
We don't need this gem.

2023-02-08 11:21 UTC, yedhink commented on Gemfile
> +  gem "dotenv", "~> 2.8.1"
No need for this one.

2023-02-08 11:21 UTC, yedhink commented on Gemfile
> +  gem "overcommit", "~> 0.59.1"
Please bring in the overcommit config too and verify the Git hooks are working as intended.

2023-02-08 11:21 UTC, yedhink commented on Gemfile
> +  gem "faraday-retry"
We don't need this gem.

2023-02-08 11:21 UTC, yedhink commented on .rubocop.yml
>    TargetRubyVersion: 3.1.2
Is there a `.ruby-version` file in this repo? If not add it.

2023-02-09 05:46 UTC, navaneethsdk commented
@yedhink _a The necessary changes have been made. Kindly review.

2023-02-09 06:11 UTC, merged